all:
	@echo "Building with Blackwell B200/B300 optimizations"	@echo "Building with Blackwell B200/B300 optimizations"	@echo "Building with Blackwell B200/B300 optimizations"	@echo "Building with Blackwell B200/B300 optimizations"CUDA_VERSION = 13.1	chmod +x run.sh

clean:
	rm -f *.o *~
