NVCC = nvcc
CUDA_VERSION = 13.1CFLAGS = -std=c++17 -O3

all: add
	@echo "Building with Blackwell B200/B300 optimizations"	@echo "Building with Blackwell B200/B300 optimizations"	@echo "Building with Blackwell B200/B300 optimizations"	@echo "Building with Blackwell B200/B300 optimizations"
add: add.cu
	$(NVCC) $(CFLAGS) -o $@ $<

clean:
	rm -f add
